---
title: "Utility Functions I Use"
author: "Nathan (Nat) Goodman"
date: "Octobr 25, 2020"
output:
  pdf_document: default
  html_document:
    css: css/html_document.css
    highlight: kate
  github_document:
    html_preview: no
linkcolor: cyan
citecolor: green
urlcolor: blue
---
<!-- README.md is generated from README.Rmd. Please edit that file -->

A collection of R utility functions I use in my recent repos and blog posts. To date, I've been writing custom utility functons for each repo, often starting from the utility functions I crafted for the previous effort. I hope to change this practice and create utility functions that are general enough and robust enough for me to use in multiple projects. Time will tell....

**THE SOFTWARE IS A WORK IN PROGRESS. THE CODE IS ROUGH and SOFTWARE DOCUMENTATION NONEXISTENT. MUCH OF THE CODE DOESN'T WORK!! PLEASE GET IN TOUCH IF YOU NEED HELP**

## Installation and Usage

The software is **not a package** and cannot be installed by `devtools::install_github` or related. Sorry. The simplest way to get the software is to download or clone the entire repo.

For my purposes, I do something even simpler. I organize my projects as a directory tree with a common root (in my cases, `~/Projects/NewPro`). I also always run the code for a given project in the project home directory, which is one below the common root (eg for my covid project, `~/Projects/NewPro/covid`). This means the code can access a given utility R file, say `plot.R` via the path `../util/R/plot.R`. 

More TBD.

## Comments Please!

Please post comments on [Twitter](https://twitter.com/gnatgoodman) or [Facebook](https://www.facebook.com/nathan.goodman.3367), or contact me by email [natg@shore.net](mailto:natg@shore.net). 

Please report bugs, other software problems, and feature requests using the [GitHub Issue Tracker](https://github.com/natgoodman/util/issues). I will be notified, and you'll be apprised of progress. As already noted, the software is still rough and software documentation nonexistent.

## Copyright & License

Copyright (c) 2020 Nathan Goodman

The software is **open source and free**, released under the [MIT License](https://opensource.org/licenses/MIT). The documentation is **open access**, released under the [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0).
